[package]
name = "receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
native-windows-gui = "1.0"
native-windows-derive = "1.0"
gstreamer = "0.20"
glib = "0.17"


[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "processthreadsapi"] }